# Generated by Django 4.2 on 2023-04-19 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='pink', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
